apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ncwu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-ikbo-tenant/byoc-app-gpbk/ncwu@sha256:7d4d5e1aeea5b6634b4f340788e137c69e76e7ea5f56418526730732f854e99c
        name: my-java-quarkus
        resources: {}
status: {}
