apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ncwu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ncwu
    app.kubernetes.io/part-of: byoc-app-gpbk
  name: ncwu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: ncwu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: ncwu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-ikbo-tenant/byoc-app-gpbk/ncwu@sha256:7d4d5e1aeea5b6634b4f340788e137c69e76e7ea5f56418526730732f854e99c
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
